server:
  port: 183


spring:
  application:
    name: nacos-conusmer  # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*' # 监控的端点

# 消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-provider













