#18006 表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 18006

# 服务别名----注册zookeeper到注册中心的名称
spring:
  application:
    name: cloud-provider-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource        #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            #mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: springcloud
    password: 123456
  cloud:
    zookeeper:
      connect-string: 192.168.199.204:2181