server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      #      # 路由配置两种方式：方式一
      routes:
        - id: payment_routh # payment_route # 路由的ID，没有固定规则但是要求唯一，建议配合服务名
#          uri: http://localhost:18001       # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE       # 匹配后提供服务名
          predicates:
            - Path=/provider/payment/getPaymentById/**   # 断言，路径相匹配的进行路由

        - id: payment_routh2 # payment_route    # 路由的ID，没有固定规则但是要求唯一，建议配合服务名
#          uri: http://localhost:18001       # 匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE       # 匹配后提供服务名
          predicates:
            - Path=/provider/payment/lb/**   # 断言，路径相匹配的进行路由
            - After=2021-03-14T17:06:20.462+08:00[Asia/Shanghai] # 指定时间的断言
#            - Before=2022-03-14T17:06:20.462+08:00[Asia/Shanghai] # 指定时间的断言
#            - Between=2021-03-14T17:06:20.462+08:00[Asia/Shanghai],2022-03-14T17:06:20.462+08:00[Asia/Shanghai] # 指定时间的过滤
#            - Cookie=username,zzyy
#            - Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
#          filter:
#            - AddRequestParameter=X-Request-Id,1024 # 过滤器工出会在匹配的请求头加上一堆请求头，名称为X-Request-Id值为1024



#      # 路由配置两种方式：方式二
#      # 代码中注入RouteLocator的Bean  ------>  com.qing.springcloud.config.GateWayConfig



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 表示是否将自己注册EurekaServer默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 设置与 Eureka Server 交互的地址，查询服务 和 注册服务都依赖这个地址
       defaultZone: http://localhost:17001/eureka/     # 单体版
#      defaultZone: http://localhost:17001/eureka/,http://eureka17002.com:17002/eureka/     #集群版