server:
  port: 19005


spring:
  application:
    name: nacos-provider  # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*' # 监控的端点













