server:
  port: 184


spring:
  application:
    name: nacos-conusmer  # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 配置nacos地址
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: 127.0.0.1:8080
        # 默认8719端口。加入被占用会自动从8719开始一次+1扫描，知道找到未被占用的端口
        # 指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*' # 监控的端点

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

# 消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-provider












